spring.application.name=gasolineras

# Puerto del servidor
server.port=8080

# Conexión PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5434/gasolineras_db
spring.datasource.username=postgres
spring.datasource.password=admin1234

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

openrouteservice.apikey=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjMyNzZiY2JhNzg0MjQ5ZTM5Y2EyZDc3NzQ4ZWViMjJmIiwiaCI6Im11cm11cjY0In0=